'use strict';
const M=HealthModel, $=id=>document.getElementById(id), KEY='health-log:v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>new Intl.NumberFormat('ja-JP',{maximumFractionDigits:2}).format(v);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
let state=M.validate(HealthSeed),selected='2026-09-12',month=selected.slice(0,7),storageBlocked=false;
function notice(message){$('notice').textContent=message;$('notice').hidden=false;}
try{const saved=localStorage.getItem(KEY);if(saved)state=M.validate(JSON.parse(saved));}catch(e){storageBlocked=true;notice('保存済みデータを読み込めませんでした。元データを保護し、一時表示しています。変更は保存されません。バックアップを読み込むと復旧できます。');}
function commit(next){state=M.validate(next);try{if(storageBlocked)throw Error();localStorage.setItem(KEY,JSON.stringify(state));notice('保存しました。このブラウザーで次回も表示できます。');}catch(e){notice('ブラウザーに保存できません。現在の記録をバックアップで書き出してください。');}render();}
const forDay=date=>state.meals.filter(m=>m.date===date).sort((a,b)=>M.categories.indexOf(a.category)-M.categories.indexOf(b.category));
function select(date){if(!M.validDate(date))return;selected=date;month=date.slice(0,7);render();}
function amount(t,n){if(!t.known)return '未確認';return `${t.estimated?'約':''}${fmt(t.value)} ${n.unit}${t.missing?'（判明分）':''}`;}
function renderCalendar(){
  const [year,mo]=month.split('-').map(Number);$('month-title').textContent=`${year}年 ${mo}月`;
  const start=new Date(year,mo-1,1),offset=(start.getDay()+6)%7,days=new Date(year,mo,0).getDate(),recorded=new Set(state.meals.map(m=>m.date));
  $('calendar').innerHTML=Array.from({length:offset},()=>'<span></span>').join('')+Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,has=recorded.has(date);return `<button data-date="${date}" class="day ${date===selected?'selected':''} ${date===today()?'today':''} ${has?'recorded':''}" aria-pressed="${date===selected}" aria-label="${date}${has?' 記録あり':''}">${i+1}<span aria-hidden="true">${has?'•':'&nbsp;'}</span></button>`;}).join('');
}
function render(){
  renderCalendar();const meals=forDay(selected),previous=M.shiftDate(selected,-1),prev=forDay(previous);
  $('day-title').textContent=new Date(selected+'T12:00:00').toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'long'});
  $('day-status').textContent=meals.length?`${meals.length}件の食事を記録${meals.some(m=>m.estimated)?' · 概算・推定値を含みます':''}`:'まだ記録がありません。「食事を記録」から追加しましょう。';
  $('nutrient-cards').innerHTML=M.nutrients.map(n=>{
    const t=M.total(meals,n.key),target=state.targets[n.key],ratio=target&&t.known?t.value/target*100:null,scale=ratio===null?150:Math.max(150,Math.ceil(ratio/50)*50),over=ratio!==null&&(n.key==='salt'?ratio>=100:ratio>100);
    return `<article class="nutrient ${over?'over':''}" style="--nutrient:${n.color}"><div class="nutrient-label">${n.label}${t.missing?'<span class="badge">一部未確認</span>':''}</div><div class="amount">${!meals.length?'—':t.known?`${t.estimated?'約':''}${fmt(t.value)}<small>${n.unit}${t.missing?' 判明分':''}</small>`:'未確認'}</div><div class="meter-label"><span>${target?`${n.key==='salt'?'上限':'目標'} ${fmt(target)}${n.unit}${n.key==='salt'?'未満':''}`:'目標未設定'}</span><strong>${ratio===null?'—':`${Math.round(ratio)}%${t.missing?' ※':''}`}</strong></div><div class="meter" ${ratio===null?'':`role="progressbar" aria-label="${n.label}${t.missing?' 判明分のみ':''}" aria-valuemin="0" aria-valuemax="${scale}" aria-valuenow="${ratio.toFixed(2)}" aria-valuetext="目安に対し${Math.round(ratio)}パーセント${t.missing?'、未確認分あり':''}"`}><span style="width:${ratio===null?0:ratio/scale*100}%"></span><i style="left:${100/scale*100}%"></i></div><p class="meter-note">${!meals.length?'記録待ち':!t.known?'値を入力すると集計できます':t.missing?'未確認分は含みません':over?(n.key==='salt'?'上限の目安に到達・超過':`目標より ${fmt(t.value-target)}${n.unit} 多め`):'記録済みの摂取量'}</p></article>`;
  }).join('');
  $('comparison-date').textContent=`${previous.replaceAll('-','/')} → ${selected.replaceAll('-','/')}`;
  $('comparison').innerHTML=!meals.length||!prev.length?`<div class="empty compact">${!prev.length?'前日の記録はまだありません。':'選択日の記録はまだありません。'}<br><small>両日の記録がそろうと、栄養素ごとの差が表示されます。</small></div>`:`<div class="table-scroll"><table><thead><tr><th>栄養素</th><th>前日</th><th>選択日</th><th>前日との差</th></tr></thead><tbody>${M.nutrients.map(n=>{const a=M.total(prev,n.key),b=M.total(meals,n.key),valid=a.known&&b.known&&!a.missing&&!b.missing,diff=Math.round((b.value-a.value)*100)/100;return `<tr><th>${n.label}</th><td>${amount(a,n)}</td><td>${amount(b,n)}</td><td>${valid?`${a.estimated||b.estimated?'約 ':''}${diff>0?'+':''}${fmt(diff)} ${n.unit}`:'比較不可（未確認）'}</td></tr>`;}).join('')}</tbody></table></div>`;
  $('meal-count').textContent=`${meals.length}件`;
  $('meals').innerHTML=meals.length?meals.map(m=>`<article class="panel meal"><div class="meal-top"><span class="meal-category">${esc(m.category)}</span>${m.estimated?'<span class="badge">概算・推定</span>':''}<div class="meal-actions"><button data-edit="${esc(m.id)}" aria-label="${esc(m.name)}を編集">編集</button><button data-delete="${esc(m.id)}" aria-label="${esc(m.name)}を削除">削除</button></div></div><h3>${esc(m.name)}</h3><div class="meal-values">${M.nutrients.map(n=>`<span>${n.label} <b>${m.nutrients[n.key]===null?'未確認':`${fmt(m.nutrients[n.key])}${n.unit}`}</b></span>`).join('')}</div>${m.note?`<p class="meal-note">${esc(m.note)}</p>`:''}</article>`).join(''):'<div class="panel empty">この日の食事を記録してみましょう。<br><button class="primary" id="empty-add">＋ 食事を記録</button></div>';
  if($('empty-add'))$('empty-add').onclick=()=>openMeal();
}
function fields(targets=false){return M.nutrients.map(n=>`<label>${n.label}（${n.unit}${targets&&n.key==='salt'?'未満':''}）<input type="number" inputmode="decimal" name="${n.key}" min="${targets?'0.01':'0'}" max="100000" step="any" ${targets&&n.key!=='fiber'?'required':''} placeholder="${targets?'任意':'未確認'}"></label>`).join('');}
$('nutrient-inputs').innerHTML=fields();$('target-inputs').innerHTML=fields(true);
function openMeal(id){const form=$('meal-form');form.reset();const m=state.meals.find(m=>m.id===id);$('form-title').textContent=m?'食事を編集':'食事を記録';form.elements.id.value=m?.id||'';form.elements.date.value=m?.date||selected;form.elements.date.min='1900-01-01';form.elements.date.max='9999-12-31';form.elements.category.value=m?.category||'朝食';form.elements.name.value=m?.name||'';form.elements.note.value=m?.note||'';form.elements.estimated.checked=m?.estimated??true;M.nutrients.forEach(n=>form.elements[n.key].value=m?.nutrients[n.key]??'');$('meal-dialog').showModal();}
$('meal-form').onsubmit=e=>{e.preventDefault();const f=e.target,number=k=>f.elements[k].value===''?null:Number(f.elements[k].value);if(!f.elements.name.value.trim()){f.elements.name.setCustomValidity('食べたものの名前を入力してください。');f.elements.name.reportValidity();return;}const m={id:f.elements.id.value||crypto.randomUUID(),date:f.elements.date.value,category:f.elements.category.value,name:f.elements.name.value.trim(),note:f.elements.note.value,estimated:f.elements.estimated.checked,nutrients:Object.fromEntries(M.nutrients.map(n=>[n.key,number(n.key)]))};try{const next={...state,meals:[...state.meals.filter(x=>x.id!==m.id),m]};M.validate(next);selected=m.date;month=selected.slice(0,7);commit(next);$('meal-dialog').close();}catch(error){notice(error.message);}};
$('meal-form').elements.name.oninput=e=>e.target.setCustomValidity('');
$('add-button').onclick=()=>openMeal();
$('meals').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit)openMeal(b.dataset.edit);if(b.dataset.delete&&confirm('この食事の記録を削除しますか？'))commit({...state,meals:state.meals.filter(m=>m.id!==b.dataset.delete)});};
$('calendar').onclick=e=>{const b=e.target.closest('[data-date]');if(b)select(b.dataset.date);};
function changeMonth(n){const d=new Date(month+'-15T12:00:00');d.setMonth(d.getMonth()+n);const y=d.getFullYear();if(y<1900||y>9999)return;month=`${y}-${String(d.getMonth()+1).padStart(2,'0')}`;renderCalendar();}
$('prev-month').onclick=()=>changeMonth(-1);$('next-month').onclick=()=>changeMonth(1);$('prev-day').onclick=()=>select(M.shiftDate(selected,-1));$('next-day').onclick=()=>select(M.shiftDate(selected,1));$('today-button').onclick=()=>select(today());
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('settings-button').onclick=()=>{M.nutrients.forEach(n=>$('settings-form').elements[n.key].value=state.targets[n.key]??'');$('settings-dialog').showModal();};
$('settings-form').onsubmit=e=>{e.preventDefault();const targets=Object.fromEntries(M.nutrients.map(n=>[n.key,e.target.elements[n.key].value===''?null:Number(e.target.elements[n.key].value)]));try{commit({...state,targets});$('settings-dialog').close();}catch(error){notice(error.message);}};
$('export-button').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`health-log-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error('ファイルは10MB以下にしてください。');const next=M.validate(JSON.parse(await file.text()));if(confirm(`${next.meals.length}件の記録と目標値を読み込み、現在の記録を置き換えます。必要なら先にバックアップを書き出してください。続けますか？`)){storageBlocked=false;commit(next);}}catch(error){notice('読み込めませんでした。'+error.message);}finally{e.target.value='';}};
render();
